/**
 * @file data.h
 * @brief Defines the PanelData class for storing and preprocessing panel survey data.
 *
 * This file contains the PanelData class, which loads the poll data
 * and category (feature/quota) information from CSV files. It performs
 * preprocessing steps including quota tightening and reordering feature values.
 */

#pragma once



/**
 * @class PanelData
 * @brief Manages pooldata including respondents, features, and quotas.
 *
 * This class encapsulates the loading, storage, preprocessing, and validation
 * of panel data.
 *
 * Preprocessing Steps Performed:
 * 1.  **Quota Tightening:** Adjusts maximum quotas (`maxVa`) based on minimum
 * quotas (`minVa`) to remove impossible scenarios. Specifically, for any
 * feature `f` and value `v`, the updated `maxVal[f][v]` becomes
 * `min(originalMaxVal[f][v], panelSize - (sum(minVal[f]) - minVal[f][v]))`.
 * 2.  **Value Reordering:** Within each feature, values are reordered 
 * by ascending maximum quota, and secondarily by descending frequency among respondents. 
 * This aims to potentially improve pruning in DP algorithms and sampling efficiency. 
 * Respondent data is remapped accordingly.
 */

class PanelData {
private:
	/** @brief The target size (number of respondents) for a valid panel. */
	int panSize;
	/** @brief The total number of distinct features (categories) tracked. */
	int totFeature;
	/** @brief Vector storing the number of distinct values for each feature. `featSize[f]` is the number of values for feature `f`. */
	vector<int> featSize;
	/** @brief 2D vector storing minimum quotas. `minVal_[f][v]` is the minimum count required for value `v` of feature `f`. */
	vector<vector<long long>> minVal;
	/** @brief 2D vector storing maximum quotas. `maxVal_[f][v]` is the maximum count allowed for value `v` of feature `f`. */
	vector<vector<long long>> maxVal;
	/** @brief Vector storing the original names of the features (read from categories file). */
	vector<string> featureName; // Note: Seems unused in provided code, but kept structure.
	/** @brief 2D vector representing respondents. `respondents_[r][f]` is the (potentially remapped) value index respondent `r` has for feature `f`. */
	vector<FeatVec> respondents;
	/** @brief 2D vector storing the mapping from original value indices to new indices after preprocessing. `valueRemap_[f][original_v] = new_v`. */
	vector<vector<int>> valueRemap; // Added to store the mapping generated by preProcess
	/** @brief Map from original feature name (string) to internal feature index (int). */
	map<string, int> featureId;
	/** @brief Vector of maps. `valueId_[f]` maps original value names (string) to internal value indices (int) for feature `f`. */
	vector<map<string, int>> valueId;



	/**
	 * @brief Performs preprocessing on pool data.
	 *
	 * This method tightens quotas and reorders values within each feature
	 * It updates `minVal_`, `maxVal_`, `respondents_`, and populates `valueRemap_`.
	 * @throw std::runtime_error If the sum of minimum quotas for any feature exceeds `panSize_`.
	 */
	void preProcess(){

		// Create copies of the raw data to work from.
		vector<vector<long long>> rawMinVal = this->minVal;
		vector<vector<long long>> rawMaxVal = this->maxVal;
		const vector<int> &featSize = this->featSize;
		vector<FeatVec> rawRespondents = this->respondents;

		// Clear the class members to be repopulated with the processed data.
		this->minVal.clear();
		this->maxVal.clear();
		this->respondents.clear();

		
		/**
		*  Tighten the upper bounds (maxVal) for each value.
		*  maxVal[v] cannot be larger than panelSize - (sum of minimums for OTHER values).	
		*/
		for (int f = 0; f < totFeature; f++){

			long long minSum = 0;
			for (long long lb : rawMinVal[f]) 
				minSum += lb;

			if (minSum > panSize)
				throw runtime_error("Infeasible: Sum of min quotas exceeds panel size.");
			
			for (size_t v = 0; v < featSize[f]; v++)
				rawMaxVal[f][v] = min(rawMaxVal[f][v], panSize - (minSum - rawMinVal[f][v]));
		}

		vector<vector<int>> featureMap(totFeature);

		for (int f = 0; f < totFeature; f++){
			vector<int> frequencies(featSize[f], 0);
		
			for (const auto& resp : rawRespondents)
				frequencies[resp[f]]++;
		
			
			vector<pair<int, int>> values;
			values.reserve(featSize[f]);
			
			for (size_t v = 0; v < featSize[f]; ++v)
				values.push_back({(int)v, frequencies[v]});
	
				
			/*
				Sorting values.
				Values with smallest ub comes first (prune the dp)
					Then the with the lasrgest number of respondents (prune sampling)

				first = Original Index
				second = Frequency        

			*/			

			sort(values.begin(), values.end(), [&](const pair<int, int>& a, const pair<int, int>& b) {
				long long maxA = rawMaxVal[f][a.first];
				long long maxB = rawMaxVal[f][b.first];
				if (maxA != maxB) 
					return maxA < maxB;

				return a.second > b.second;
				
			});
			
			// Build the featureMap and the final, processed quota vectors.
			featureMap[f].resize(featSize[f]); // Resize to hold all original values.
			
			vector<long long> finalMin, finalMax;
			for (size_t i = 0; i < values.size(); ++i){
				int oldId = values[i].first;
			
				featureMap[f][oldId] = i; // Map the original index to its new, sorted position.
			
				finalMin.push_back(rawMinVal[f][oldId]);
				finalMax.push_back(rawMaxVal[f][oldId]);
			}

			this->minVal.push_back(finalMin);
			this->maxVal.push_back(finalMax);
		}

		// Remap respondent feature vectors
		for (size_t i = 0; i < rawRespondents.size(); ++i) {
			FeatVec newResp(totFeature);
			for (int f = 0; f < totFeature; f++) 
				newResp[f] = featureMap[f][rawRespondents[i][f]];
			this->respondents.push_back(newResp);
		}
	}



public:

	/**
	 * @brief Constructs PanelData by loading configuration from CSV files.
	 *
	 * Reads category/feature definitions (including quotas) and respondent data.
	 * Performs preprocessing (quota tightening, value reordering) after loading.
	 *
	 * @param panelSize The target number of respondents for a valid panel. Must be > 0.
	 * @param categoriesFile Path to the CSV file defining features, values, and quotas.
	 * Expected format (after header): FeatureName,ValueName,MinQuota,MaxQuota
	 * @param respondentsFile Path to the CSV file listing respondents and their values.
	 * Expected header: ID,FeatureName1,FeatureName2,...
	 * Expected data rows: respondentID,ValueName1,ValueName2,...
	 * Feature names in the header must match names in the categories file.
	 * Value names in data rows must match names for the corresponding feature
	 * in the categories file.
	 * @throw std::runtime_error If files cannot be opened, data is empty/malformed,
	 * parsing fails, not enough valid respondents are found, or preprocessing
	 * detects infeasibility.
	 * @throw std::invalid_argument If panelSize is zero.
	 */
	PanelData(long long pSize, const string& categoriesFile, const string& respondentsFile)
		: panSize(pSize){

		try {   
			assert(panSize > 0);

			vector<vector<string>> categoriesData, respondentsData;

			try{
				categoriesData = readCSV(categoriesFile);
				respondentsData = readCSV(respondentsFile);

				if (categoriesData.empty() || respondentsData.empty())
					throw runtime_error("Failed to load panel data files.");
			}
			catch (const std::runtime_error& e){
				cerr << RED << "Error reading the CSV files " << WHITE << e.what() << endl;
				exit(0);
			}

			categoriesData.erase(categoriesData.begin()); // Remove CSV Header


			/*
				Converts the feature names into indexes
			*/

			totFeature = 0;
			for (const auto& v : categoriesData){
				if (!featureId.count(v[0])) // New feature
					featureId[v[0]] = totFeature++;
			}

			
			minVal.resize(totFeature); 
			maxVal.resize(totFeature);

			featSize.resize(totFeature);
			fill(featSize.begin(), featSize.end(), 0);

			valueId.resize(totFeature);


			for (const auto& v : categoriesData){
				
				int fId = featureId[v[0]];

				if (!valueId[fId].count(v[1])){
					valueId[fId][ v[1] ] = featSize[fId];
					featSize[fId]++;
				}

				minVal[fId].push_back(stoi(v[2]));
				maxVal[fId].push_back(stoi(v[3]));
			}


			respondents.reserve(respondentsData.size());

			for (size_t i = 1; i < respondentsData.size(); i++){
				FeatVec aux(totFeature);
				for (size_t j = 1; j < respondentsData[i].size(); j++){
					int fId = featureId[ respondentsData[0][j] ];
					if (!valueId[ fId ].count(respondentsData[i][j]))
						throw std::runtime_error("respondent data mismatch");
					aux[ fId  ] = valueId[ fId ][ respondentsData[i][j] ];
				}

				respondents.push_back(aux);
			}

			if (__verbose_mode){
				map<FeatVec, int> profileFreq;
				for (auto resp: respondents)
					profileFreq[resp]++;

				int minFreq = respondents.size();
				for (auto prof : profileFreq)
					minFreq = min(minFreq, prof.second);
			
				int maxFreq = 0;
				for (auto prof : profileFreq)
					maxFreq = max(maxFreq, prof.second);
				
				cerr << YELLOW << "Instance data:" << endl;
				cerr << YELLOW << "\tNumber of respondents: " << WHITE << respondents.size() << endl;
				cerr << YELLOW << "\tNumber of distinct feature-value profiles: " << WHITE << profileFreq.size() << endl;
				cerr << YELLOW << "\t\tMin number of ocurrences of a fv profile: " << WHITE << minFreq << endl;
				cerr << YELLOW << "\t\tMax number of ocurrences of a fv profile: " << WHITE << maxFreq << endl;
				cerr << YELLOW << "\tNumber of features: " << WHITE << totFeature << endl; 
				cerr << YELLOW << "\tNumber of Values: " << WHITE;
				for (int i = 0; i < totFeature; i++)
					cerr << featSize[i] << ' ';
				cerr << endl << endl;

			}

			assert(respondents.size() >= panSize);

			this->preProcess();

		} catch (const runtime_error& e) {
			cerr << "Error loading data: " << e.what() << endl;
			exit(1);
		}


	}

	/**
	 * @brief Constructs a new PanelData object by applying value mappings to an existing one.
	 * 
	 * Quotas for merged values are aggregated (sum of mins, sum of maxs).
	 *
	 * @param originalData The PanelData object to transform.
	 * @param valueMaps A 2D vector where `valueMaps[f][original_v]` gives the new value index `new_v`
	 * for original value `original_v` of feature `f`.
	 * @pre `valueMaps` must have size equal to `originalData.getTotFeature()`.
	 * @pre For each feature `f`, `valueMaps[f]` must have size equal to `originalData.getFeatSize()[f]`.
	 * @pre Within each `valueMaps[f]`, the resulting new indices must be contiguous starting from 0
	 * (e.g., if the highest new index is 3, then 0, 1, and 2 must also appear).
	 * @throw std::runtime_error If preprocessing detects infeasibility in the new data.
	 */
	PanelData(const PanelData& originalData, const vector<vector<int>>& valueMaps){
		this->panSize = originalData.getPanSize();
		this->totFeature = originalData.getTotFeature();

		assert(valueMaps.size() == this->totFeature);

		for (int f = 0; f < this->totFeature; f++){
			
			int newSz = 0;
			if (!valueMaps[f].empty()){
				set<int> newIds(valueMaps[f].begin(), valueMaps[f].end());

				int maxId = *newIds.rbegin(); // largest if
				assert(newIds.size() == (size_t)(maxId + 1) && "Value map is not contiguous.");
				
				// The new size is 1 + the largest index.
				newSz = maxId + 1;
			}
			this->featSize.push_back(newSz);

			vector<long long> newMinVal(newSz, 0);
			vector<long long> newMaxVal(newSz, 0);
			

			// Bound of 
			for (int v = 0; v < valueMaps[f].size(); v++) {
				newMinVal[valueMaps[f][v]] += originalData.getMinVal()[f][v];
				newMaxVal[valueMaps[f][v]] += originalData.getMaxVal()[f][v];
			}

			this->minVal.push_back(newMinVal);
			this->maxVal.push_back(newMaxVal);
		}

		/*
			Warning: new respondent vector has the same indices as the old one
			This is fundamental for the sampling process to work as intended
		*/
		for (const auto& oRId : originalData.getRespondents()){
			
			FeatVec newResp(this->totFeature);
			
			for (int f = 0; f < this->totFeature; f++)
				newResp[f] = valueMaps[f][oRId[f]];
			
			this->respondents.push_back(newResp);
		}

		this->preProcess();
	}

	/**
	 * @brief Checks if a given panel (list of respondent indices) is valid.
	 *
	 * A panel is valid if:
	 * 1. It contains exactly `panSize` respondents.
	 * 2. For every feature `f` and every value `v`, the count of respondents
	 * in the panel having value `v` for feature `f` is within the range
	 * `[minVal_[f][v], maxVal_[f][v]]`.
	 *
	 * @param panel A vector of respondent indices (referring to `respondents`).
	 * @return `true` if the panel is valid, `false` otherwise.
	 */
	bool isValid(const vector<int>& panel) const {
		if (panel.size() != panSize)
			return false;

		vector<vector<int>> panValues(totFeature);
		for (int i = 0; i < totFeature; i++)
			panValues[i].resize(featSize[i], 0);
		
		for (int rId : panel){
			for (int f = 0; f < totFeature; f++){
				int val = respondents[rId][f];
				panValues[f][val]++;
				
				// Max Quota
				if (panValues[f][val] > maxVal[f][val])
					return false;
			}
		}
		
		// Min Quota
		for (int f = 0; f < totFeature; f++){
			for (int v = 0; v < featSize[f]; v++){
				if (panValues[f][v] < minVal[f][v])
					return false;
			}
		}
		return true;
	}


	inline long long getTotFeature() const { return totFeature; }
	inline long long getPanSize() const { return panSize; }
	const vector<vector<long long>>& getMinVal() const { return minVal; }
	const vector<vector<long long>>& getMaxVal() const { return maxVal; }
	const vector<int>& getFeatSize() const { return featSize; }
	const vector<FeatVec>& getRespondents() const { return respondents; }
};